version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    environment:
      - DATABASE_URL=postgresql://mayday:mayday@db:5432/mayday
      - SESSION_SECRET_KEY=ZyGY57QltLWD7QMuYz3LADwGjzgsjwCl
    ports:
      - '3000:3000'
  db:
    restart: unless-stopped
    image: postgres:14.1
    environment:
      - POSTGRES_USER=mayday
      - POSTGRES_PASSWORD=mayday
      - POSTGRES_DB=mayday
    volumes:
      - mayday-db:/var/lib/postgresql/data
    ports:
      - '7064:5432'

volumes:
  mayday-db:
    name: mayday-db
