@startuml Class Diagram

namespace Order {
  class OrderQueries <<Controller>> {
    + int countSoldOrders()
    + Order getOrder()
    + Order[] getOrders()
    + Order[] getShopOrders()
  }

  class OrderMutations <<Controller>> {
    + Order updateOrderStatus()
  }
}

namespace Review {

  class ReviewQueries <<Controller>> {
    + (double, int) getRating()
    + Review[] getReviews()
  }

  class ReviewMutations <<Controller>> {
    + Review writeReview()
  }

}

namespace Prisma {
  class Order <<Repository>> {
    + {static} findFirst()
    + {static} findUnique()
    + {static} findMany()
    + {static} create()
    + {static} update()
    + {static} count()
  }

  class Review <<Repository>> {
    + {static} findMany()
    + {static} createMany()
    + {static} aggregate()
  }

  Order.OrderQueries "1..1" -- "1..1" Order: call >
  Order.OrderMutations "1..1" -- "1..1" Order: call >
  Review.ReviewQueries "1..1" -- "1..1" Review: call >
  Review.ReviewMutations "1..1" -- "1..1" Review: call >
  Review.ReviewMutations "1..1" -- "1..1" Order: call >
}


class ProductDetailPage <<Boundary>> {}
class ShopProfilePage <<Boundary>> {}
class WriteReviewPage <<Boundary>> {}
class ShopOrderDetailPage <<Boundary>> {}
class ShopOrderListPage <<Boundary>> {}
class UserOrderListPage <<Boundary>> {}

ProductDetailPage "0..*" -- "1..1" Review.ReviewQueries: >
ShopProfilePage "0..*" -- "1..1" Review.ReviewQueries: >
WriteReviewPage "0..*" -- "1..1" Review.ReviewMutations: >

ShopOrderDetailPage "0..*" -- "1..1" Order.OrderQueries: >
ShopOrderListPage "0..*" -- "1..1" Order.OrderQueries: >
UserOrderListPage "0..*" -- "1..1" Order.OrderQueries: >
ShopOrderDetailPage "0..*" -- "1..1" Order.OrderMutations: >


@enduml
