@startuml Class Diagram

namespace Order {
  class Order <<Entity>> {
    + id: number
    + owner: User
    + shop: Shop

    + status: OrderStatus
    + totalPrice: number
    + chargeId: string
    + items: OrderItemSnapshot

    + address: string
    + addressNote: string
    + receiverName: string
    + receiverPhoneNo: string

    + transaction: Transaction[]

    + {static} findFirst()
    + {static} findUnique()
    + {static} findMany()
    + {static} create()
    + {static} update()
    + {static} count()
  }

  class OrderItemSnapshot <<Entity>> {
    + id: number
    + order: Order
    + product: Product

    + name: string
    + description: string
    + price: float
    + soldPrice: float
    + images: string[]
  }

  Order "1..1" -- "0..*" OrderItemSnapshot: contains >

  class OrderQueries <<Controller>> {
    + int countSoldOrders()
    + Order getOrder()
    + Order[] getOrders()
    + Order[] getShopOrders()
  }

  class OrderMutations <<Controller>> {
    + Order updateOrderStatus()
  }

  OrderQueries "1..1" -- "0..*" Order: queries >
  OrderMutations "1..1" -- "1..*" Order: mutates >
}

namespace Review {
  class Review <<Entity>> {
    + id: number
    + shop: Shop
    + user: User
    + product: Product
    + rating: float
    + title: string
    + comment: string

    + {static} findMany()
    + {static} createMany()
    + {static} aggregate()
  }

  class ReviewQueries <<Controller>> {
    + (double, int) getRating()
    + Review[] getReviews()
  }

  class ReviewMutations <<Controller>> {
    + Review writeReview()
  }

  ReviewQueries "1..1" -- "0..*" Review: queries >
  ReviewMutations "1..1" -- "1..*" Review: mutates >
  ReviewMutations "1..1" -- "1..*" Order.Order: queries and mutates >
}


class ProductDetailPage <<Boundary>> {}
class ShopProfilePage <<Boundary>> {}
class WriteReviewPage <<Boundary>> {}
class ShopOrderDetailPage <<Boundary>> {}
class ShopOrderListPage <<Boundary>> {}
class UserOrderListPage <<Boundary>> {}

ProductDetailPage "0..*" -- "1..1" Review.ReviewQueries: >
ShopProfilePage "0..*" -- "1..1" Review.ReviewQueries: >
WriteReviewPage "0..*" -- "1..1" Review.ReviewMutations: >

ShopOrderDetailPage "0..*" -- "1..1" Order.OrderQueries: >
ShopOrderListPage "0..*" -- "1..1" Order.OrderQueries: >
UserOrderListPage "0..*" -- "1..1" Order.OrderQueries: >
ShopOrderDetailPage "0..*" -- "1..1" Order.OrderMutations: >


@enduml
