@startuml Deployment Diagram

node Railway <<cloud>> {
  node "mayday-app" as appContainer <<container>> {
    node "Node.js" <<execution environment>>{
      component "mayday app server" as maydayApp <<component>>
    }
  }

  node "mayday-db" as db <<container>> {
    component PostgreSQL <<component>>
  }

  appContainer -- db
}

node "Google Cloud Platform" <<cloud>> {
  node "Google Cloud Storage Bucket" as gcs <<storage>>
}

node "User's device" <<device>> as device {
  node "browser" <<execution environment>> {
    artifact "Frontend Assets" <<artifact>>
  }
}

device -- appContainer
appContainer -- gcs

@enduml
